import { type NextPage } from 'next'
import Head from 'next/head'
import { env } from '~/env.mjs'
import axios from 'axios'

const Home: NextPage = () => {
  const handleEdgeFunction = () => {
    console.log('clicked brain at: ', new Date().toLocaleString())
    axios
      .post(
        'http://localhost:54321/functions/v1/brain', // local
        // 'https://tpqbderafyftvmrhrdht.functions.supabase.co/brain', // prod
        {
          // yt_url: 'https://www.youtube.com/watch?v=gGZmi3UVSOI',
          yt_url: 'https://www.youtube.com/watch?v=u7j--YMXZtA', // french mbappe song
          // yt_url:
          //   'https://www.youtube.com/watch?v=u7j--YMXZtA&list=RDu7j--YMXZtA', // youtube mix
          desired_language: 'en',
        },
        {
          headers: {
            Authorization: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0`, // local
            // Authorization: `Bearer ${env.NEXT_PUBLIC_SUPABASE_ANON_KEY}`, // prod
            'Content-Type': 'application/json',
          },
        },
      )
      .then((response) => {
        console.log(response.data)
      })
      .catch((error) => {
        console.error(error)
      })
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <button
          className="rounded-lg bg-white p-6"
          onClick={() => handleEdgeFunction()}
        >
          🧠 on {process.env.NODE_ENV}
        </button>
      </main>
    </>
  )
}

export default Home
